
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RDECLARE = 31;
  public static final int MENQUE = 17;
  public static final int RSTRING = 33;
  public static final int RTRUE = 15;
  public static final int RWHILE = 40;
  public static final int POR = 12;
  public static final int CONCAT = 14;
  public static final int ENTERO = 26;
  public static final int RVOID = 44;
  public static final int RFALSE = 16;
  public static final int LLAVIZQ = 6;
  public static final int RELSE = 39;
  public static final int IDENTIFICADOR = 36;
  public static final int RPRINT = 30;
  public static final int IGUAL = 35;
  public static final int IGUALQUE = 22;
  public static final int CORDER = 9;
  public static final int DIVIDIDO = 13;
  public static final int MAYIGUALQUE = 20;
  public static final int UMENOS = 29;
  public static final int RDO = 41;
  public static final int EOF = 0;
  public static final int PARIZQ = 4;
  public static final int DECIMAL = 27;
  public static final int MENIGUALQUE = 19;
  public static final int RELSEIF = 38;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int CADENA = 28;
  public static final int MENOS = 11;
  public static final int MAYQUE = 18;
  public static final int LLAVDER = 7;
  public static final int RRETURN = 45;
  public static final int RNUMBER = 32;
  public static final int PTCOMA = 3;
  public static final int ROR = 24;
  public static final int RBOOLEAN = 34;
  public static final int RFOR = 42;
  public static final int PARDER = 5;
  public static final int CORIZQ = 8;
  public static final int RBREAK = 46;
  public static final int RIF = 37;
  public static final int RFUNCTION = 43;
  public static final int RNOT = 23;
  public static final int RAND = 25;
  public static final int DIFQUE = 21;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVIZQ",
  "LLAVDER",
  "CORIZQ",
  "CORDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "CONCAT",
  "RTRUE",
  "RFALSE",
  "MENQUE",
  "MAYQUE",
  "MENIGUALQUE",
  "MAYIGUALQUE",
  "DIFQUE",
  "IGUALQUE",
  "RNOT",
  "ROR",
  "RAND",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "RPRINT",
  "RDECLARE",
  "RNUMBER",
  "RSTRING",
  "RBOOLEAN",
  "IGUAL",
  "IDENTIFICADOR",
  "RIF",
  "RELSEIF",
  "RELSE",
  "RWHILE",
  "RDO",
  "RFOR",
  "RFUNCTION",
  "RVOID",
  "RRETURN",
  "RBREAK"
  };
}

